name: Build and Push Docker Image with Tags

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

env:
  IMAGE_NAME: spiderto/tjp-backend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up tag environment
        id: tag_vars
        run: |
          echo "TAG_DATE=$(date +'%Y.%m.%d-%H%M')" >> $GITHUB_ENV
          echo "TAG_GIT=${GITHUB_SHA::7}" >> $GITHUB_ENV
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            echo "TAG_REF=${GITHUB_REF##*/}" >> $GITHUB_ENV
          else
            echo "TAG_REF=" >> $GITHUB_ENV
          fi

      - name: Show tags
        run: |
          echo "🕒 Date Tag: $TAG_DATE"
          echo "🔧 Git SHA: $TAG_GIT"
          echo "🏷️ Tag Ref: $TAG_REF"

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Tag Docker Image
        run: |
          docker build -t $IMAGE_NAME:$TAG_DATE .
          docker tag $IMAGE_NAME:$TAG_DATE $IMAGE_NAME:latest
          docker tag $IMAGE_NAME:$TAG_DATE $IMAGE_NAME:$TAG_GIT
          if [ ! -z "$TAG_REF" ]; then
            docker tag $IMAGE_NAME:$TAG_DATE $IMAGE_NAME:$TAG_REF
          fi

      - name: Push Docker Tags
        run: |
          docker push $IMAGE_NAME:$TAG_DATE
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:$TAG_GIT
          if [ ! -z "$TAG_REF" ]; then
            docker push $IMAGE_NAME:$TAG_REF
          fi

      - name: Create GitHub Release (if tag)
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
